# barberia/docker-compose.yml

version: "3.8"

services:
  # Serviço para o Frontend do Cliente
  frontend:
    build:
      context: ./frontend
      args:
        # Você pode passar a URL da sua API de produção aqui
        VITE_API_URL: ${VITE_API_URL_PROD}
    container_name: barbershop-frontend-client
    restart: unless-stopped
    ports:
      # Expõe a porta 80 do contêiner na porta 8081 da sua máquina/servidor
      # O Coolify vai gerenciar isso, então os números exatos podem ser ajustados lá
      - "8081:80"

  # Serviço para o Painel Admin
  admin:
    build:
      context: ./admin-frontend
      args:
        VITE_API_URL: ${VITE_API_URL_PROD}
    container_name: barbershop-frontend-admin
    restart: unless-stopped
    ports:
      - "8082:80"

  # Serviço para o Backend
  backend:
    build:
      context: ./backend
    container_name: barbershop-backend-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      # Carrega as variáveis de ambiente do arquivo .env dentro da pasta do backend
      - ./backend/.env
    # Se você também fosse rodar um banco de dados Mongo em Docker,
    # você adicionaria ele como outro serviço aqui e os conectaria em uma rede.

# Opcional: Definir uma rede customizada para os serviços
networks:
  default:
    name: barbershop_network
